require_relative "../config/environment.rb"

User.create(username: "Mr. Potatohead")
User.create(username: "Rock Rockles")
User.create(username: "Steve")
User.create(username: "Barack Obama")
User.create(username: "Lil Uzi Vert")
User.create(username: "Aunt Jemima")
User.create(username: "Chuck Norris")
User.create(username: "Floopy Nooples")
User.create(username: "Grandpa Rick")
User.create(username: "Slug Christ")
User.create(username: "Ash Ketchum")
User.create(username: "MangoMan Dan")
User.create(username: "Dante from the DMC series")
User.create(username: "Tony Hawk")
User.create(username: "Kate Upton")
User.create(username: "Kim Kardashian")
User.create(username: "My Boi Boris")
User.create(username: "Nathaniel Sagman")
User.create(username: "Piccolo")
User.create(username: "Naruto")
User.create(username: "Luffy")

Show.create(title: "Bill and Ted's Excellent Adventure", genre: "Comedy")
Show.create(title: "The Matrix", genre: "Action")
Show.create(title: "The Office", genre: "Comedy")
Show.create(title: "Back to the Future", genre: "Comedy")
Show.create(title: "Naruto", genre: "Anime")
Show.create(title: "One Piece", genre: "Anime")
Show.create(title: "Judge Judy", genre: "Reality")
Show.create(title: "Fear Factor", genre: "Reality")
Show.create(title: "Kill la Kill", genre: "Anime")
Show.create(title: "Jersey Shore", genre: "Reality")
Show.create(title: "Code Geass", genre: "Anime")
Show.create(title: "Avatar: The Last Airbender", genre: "Cartoon")
Show.create(title: "Ed Edd and Eddy", genre: "Cartoon")
Show.create(title: "Ghost in the Shell", genre: "Scifi")
Show.create(title: "Dragonball Z", genre: "Anime")
Show.create(title: "Powerpuff Girls", genre: "Cartoon")
Show.create(title: "Parks and Rec", genre: "Comedy")
Show.create(title: "Game of Thrones", genre: "Fantasy")
Show.create(title: "Lost", genre: "Mystery")
Show.create(title: "Dora the Explorer", genre: "Cartoon")

User.all[0].like_show(1)
User.all[0].like_show(2)
User.all[0].like_show(3)
User.all[0].like_show(4)
User.all[0].like_show(5)
User.all[0].like_show(6)
User.all[0].like_show(7)
User.all[0].like_show(8)
User.all[0].like_show(9)
User.all[0].like_show(10)
User.all[0].like_show(11)
User.all[0].like_show(12)
User.all[0].like_show(13)
User.all[0].like_show(14)
User.all[0].like_show(15)
User.all[2].like_show(3)
User.all[4].like_show(4)
User.all[3].like_show(5)
User.all[8].like_show(6)
User.all[7].like_show(7)
User.all[5].like_show(8)
User.all[2].like_show(9)
User.all[10].like_show(10)
User.all[11].like_show(11)
User.all[15].like_show(12)
User.all[17].like_show(13)
User.all[7].like_show(1)
User.all[1].like_show(2)
User.all[8].like_show(3)
User.all[14].like_show(4)
User.all[16].like_show(5)
User.all[14].like_show(6)
User.all[13].like_show(7)
User.all[18].like_show(8)
User.all[20].like_show(9)
User.all[17].like_show(10)
User.all[4].like_show(11)
User.all[5].like_show(12)
User.all[8].like_show(13)
User.all[10].like_show(14)
User.all[20].like_show(15)
User.all[12].like_show(3)
User.all[5].like_show(4)
User.all[9].like_show(5)
User.all[13].like_show(6)
User.all[19].like_show(7)
User.all[9].like_show(8)
User.all[10].like_show(9)
User.all[10].like_show(10)
User.all[1].like_show(11)
User.all[3].like_show(12)
User.all[2].like_show(13)
